# This file defines the Rust style for automatic reformatting.
# See also https://rust-lang.github.io/rustfmt

# Version of the formatting rules to use.
# NOTE: Nightly only
#version = "Two"

# Line endings will be converted to \n.
newline_style = "Unix"

# NOTE: Nightly only
#wrap_comments = true

# The "Default" setting has a heuristic which splits lines too aggresively.
# We are willing to revisit this setting in future versions of rustfmt.
# Bugs:
# * https://github.com/rust-lang/rustfmt/issues/3119
# * https://github.com/rust-lang/rustfmt/issues/3120
use_small_heuristics = "Max"