# Copyright 2023 The resback authors

[package]
name = "resback"
version = "0.1.0"
edition = "2021"
authors = ["Qoo <akck0918@gmail.com>"]
description = "Respec.team's backend"
repository = "https://github.com/choijunhyuck/resback"
# We do not want to publish this
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
dotenv = "0.15.0"
oauth2 = "4.4.1"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "mysql", "chrono", "time"] }
tokio = { version = "1.28.2", features = ["full"] }

[dev-dependencies]
tower = { version = "0.4.13", features = ["util"] }
