#!/bin/bash

echo "Building docker images for each architecture..."

source ./hooks/architectures

if [[ -z "${SOURCE_COMMIT}" ]]; then
  SOURCE_COMMIT="$(git rev-parse HEAD)"
fi

# Construct a version string in the style of `build.rs`.
GIT_EXACT_TAG="$(git describe --tags --abbrev=0 --exact-match 2>/dev/null)"
if [[ -n "${GIT_EXACT_TAG}" ]]; then
  SOURCE_VERSION="${GIT_EXACT_TAG}"
else
  GIT_LAST_TAG="$(git describe --tags --abbrev=0)"
  SOURCE_VERSION="${GIT_LAST_TAG}-${SOURCE_COMMIT:0:8}"
fi

LABELS=(
  # https://github.com/opencontainers/image-spec/blob/master/annotations.md
  org.opencontainers.image.created="$(date --utc --iso-8601=seconds)"
  org.opencontainers.image.documentation="https://github.com/dani-garcia/vaultwarden/wiki"
  org.opencontainers.image.licenses="AGPL-3.0-only"
  org.opencontainers.image.revision="${SOURCE_COMMIT}"
  org.opencontainers.image.source="${SOURCE_REPOSITORY_URL}"
  org.opencontainers.image.url="https://github.com/dani-garcia/vaultwarden"
  org.opencontainers.image.version="${SOURCE_VERSION}"
)
LABEL_ARGS=()
for label in "${LABELS[@]}"; do
  LABEL_ARGS+=(--label "${label}")
done

set -ex

for architecture in "${architectures[@]}"; do
  docker build \
         "${LABEL_ARGS[@]}" \
         --tag "${REPOSITORY}:${DOCKER_TAG}-${architecture}" \
         -f "./docker/${architecture}/Dockerfile" \
         ./
done
